builds:
  - main: main.go
    binary: acme-dns
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - netbsd
      - openbsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: arm64

archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
    - goos: darwin
      format: zip
  replacements:
    amd64: 64bit
    386: 32bit
    darwin: macOS
  files:
    - LICENSE
    - README.md
    - Dockerfile
    - config.cfg
